DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS image;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE image (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  taken TIMESTAMP,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  file_size INTEGER NOT NULL,
  file_name TEXT NOT NULL,
  owner INTEGER NOT NULL,
  image_embedding blob,
  FOREIGN KEY (owner) REFERENCES user (id)
);

CREATE VIRTUAL TABLE vss_image using vss0 (
  image_embedding(512),
);
